# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

#ワークフロー名					
name: Java CI with Gradle					
					
#メインブランチがプッシュされたときに実行					
on:					
  push:					
    branches: [ "main" ]					
					
permissions:					
  contents: read					
					
jobs:					
  build:									
    runs-on: ubuntu-latest					
					
    steps:						
    - uses: actions/checkout@v3						
    - name: Install JDK 17					
      uses: actions/setup-java@v3					
      with:					
        java-version: '17'					
        distribution: 'adopt'								
    - name: gradlew permission					
      run: chmod +x ./gradlew    					 					
    - name: Build with Gradle					
      run: ./gradlew build jacocoTestReport					
    - name: Archive unit test results					
      uses: actions/upload-artifact@v2					
      with:					
        name: unit-test-report					
        path: build/reports/tests/test					
    # カバレッジレポート出力(Jacoco)					
    - name: Archive coverage results					
      uses: actions/upload-artifact@v2					
      with:					
        name: code-coverage-report					
        path: build/reports/jacoco/test/html					

